global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1

scrape_configs:
  - job_name: nginx
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets: ['nextro.in:9113']
  - job_name: node
    metrics_path: /metrics
    static_configs:
      - targets: ['nextro.in:9100']
  - job_name: server1_db
    static_configs:
      - targets: ['nextro.in:9104']
        labels:
          alias: db1
